### ISSUE TITLE
Timezone and policy hub values are unexected in AIX

### ISSUE THREAD

**Issue by flynn1973** [neilhwatson/delta_reporting#31]
Agent Platform: IBM AIX wiht olson timezone set
Perl Version: 5.20
DR Tag: latest

root@sag0130: /var/cfengine/delta_reporting/log # head classes
BEGIN 2016-11-24T09:52:23CET
have_fs___mounts_147__2__
GMT_Day24
have_fs_kind
November
have_fs___mounts_112__2__
have_fs___mounts_185__2_____mounts_185__1__
have_fs___mounts_15__1__
ipv4_172_16
services_autorun
root@sag0130: /var/cfengine/delta_reporting/log # head promises
BEGIN 2016-11-24T09:52:23CET
root@sag0130: /var/cfengine/delta_reporting/log # head final
2016-11-24T09:42:26CET ;; have_fs___mounts_147__2__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; GMT_Day24 ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; have_fs_kind ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; November ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; have_fs___mounts_112__2__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; have_fs___mounts_185__2_____mounts_185__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; have_fs___mounts_15__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; ipv4_172_16 ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; services_autorun ;; empty ;; empty ;; empty ;; empty
2016-11-24T09:42:26CET ;; have_fs__ ;; empty ;; empty ;; empty ;; empty

root@nimmsag: /var/cfengine/outputs # perl /opt/delta_reporting/app/script/load /var/cfengine/delta_reporting/log/client_logs/172.17.14.5.log
[Wed Nov 23 15:40:09 2016] [debug] Reading configuration file "/opt/delta_reporting/app/DeltaR.conf"
hostname: Not a recognized flag: -
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server timestamp, skipping record at lib/DeltaR/Query.pm line 536

i tested the strftime variables %z %Z, and the output is always CET and no numeric offset value, while manpage says otherwise.

root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # cat strftime_test.c
#include <stdio.h>
#include <time.h>

int main ()
{
   time_t rawtime;
   struct tm *info;
   char buffer[80];

   time( &rawtime );

   info = localtime( &rawtime );

   strftime(buffer,80,"%Y-%m-%dT%H:%M:%S%Z", info);
   printf("Formatted date & time : |%s|\n", buffer );

   return(0);
}
root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # xlc_r -o strftime_test strftime_test.c
root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # ./strftime_test
Formatted date & time : |2016-11-24T10:00:44CET|

root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # cat strftime_test.c
#include <stdio.h>
#include <time.h>

int main ()
{
   time_t rawtime;
   struct tm *info;
   char buffer[80];

   time( &rawtime );

   info = localtime( &rawtime );

   strftime(buffer,80,"%Y-%m-%dT%H:%M:%S%z", info);
   printf("Formatted date & time : |%s|\n", buffer );

   return(0);
}
root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # xlc_r -o strftime_test strftime_test.c
root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # ./strftime_test
Formatted date & time : |2016-11-24T10:01:55CET|

i also tested with posix timezone setting with same results.

ist %z of any significant importance or can it be ommited?

**Comment by flynn1973** [comment]
i testet with a manually formated logfile, now whines about policy_server not valid?

2016-11-24T10:23:14-100 ;; GMT_Day24 ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs_kind ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; November ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs___mounts_15__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; ipv4_172_16 ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; services_autorun ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs___mounts_199__2_____mounts_199__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs___mounts_271__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs_Licensed ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; _stdlib_path_exists_df ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; _stdlib_has_path_diff ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs___mounts_250__2__ ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs___mount ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; _stdlib_has_path_logger ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; ipv4_172 ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; GMT_Q2 ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; smtp_in_high ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; Min23 ;; empty ;; empty ;; empty ;; empty
2016-11-24T10:23:14-100 ;; have_fs___mounts_125__1__ ;; empty ;; empty ;; empty ;; empty


ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536
ERROR: These inputs for Validator::client_log are invalid:  policy_server, skipping record at lib/DeltaR/Query.pm line 536

**Comment by neilhwatson** [comment]
It looks like an AIX bug to me. I may be able to rig a work around but, I don't have access to AIX, so I rely on you to tell me how to get the correct timestamp from it. Still looking at the other error.

**Comment by neilhwatson** [comment]
The program expects an IP address to fqhn.
https://github.com/neilhwatson/delta_reporting/blob/master/app/lib/DeltaR/Validator.pm#L122

The perl program looks this up:
https://github.com/neilhwatson/delta_reporting/blob/master/app/lib/DeltaR/Query.pm#L509

Again looks like an AIX thing. Can confirm?

**Comment by flynn1973** [comment]
the first one is cleary a bug in the aix strftime implementation and i filed a pmr at ibm. will keep you updated on this.
the second one is still a mystery to me. where should this ip adress come from?

**Comment by neilhwatson** [comment]
Hostname or IP address comes from this module: https://metacpan.org/pod/Sys::Hostname::Long

**Comment by flynn1973** [comment]
the test script of the Sys::Hostname module seems to work.

root@nimmsag: /usr/opt/perl5/lib/site_perl/5.20.1/Sys/Hostname # ./testall.pl nimmsag
hostname: Not a recognized flag: -
Method           |Title                            |Result
-----------------|---------------------------------|---------------------------------------
AUTOMATIC        |via exec_hostname_fqdn           |Usage: hostname [-s] [Host].
exec_hostname    |Execute "hostname"               |nimmsag
exec_hostname_dom|Execute "hostname" and "domainnam|nimmsag.
hostname: Not a recognized flag: -
exec_hostname_fqd|Execute "hostname --fqdn"        |Usage: hostname [-s] [Host].
gethostbyname    |Get Host by Name                 |
ip               |Network Socket IP then Hostname v|172.16.100.191
network          |Network Socket hostname (not DNS)|nimmsag
uname            |POSIX::uname                     |nimmsag
win32_registry1  |WIN32 Registry                   |
win32_registry2  |WIN32 Registry                   |

root@nimmsag: /usr/opt/perl5/lib/site_perl/5.20.1/Sys/Hostname # host nimmsag
nimmsag is 172.16.100.191,  Aliases:   nimmsag.sozvers.at

**Comment by flynn1973** [comment]
just to make sure, the policy host has multiple network interfaces and cfengine ist bootstraped to 172.17.8.1, not to the above mentioned 172.16.100.191.  i dont know if this is of any importance.

**Comment by neilhwatson** [comment]
What does this test program return?

   #!/usr/bin/perl

   use Sys::Hostname::Long 'hostname_long';
   use feature 'say';
   use strict;
   use warnings;

   say hostname_long();

**Comment by neilhwatson** [comment]
Here's a complete test for hostname:

   #!/usr/bin/perl

   use Sys::Hostname::Long 'hostname_long';
   use Regexp::Common qw/ net number /;
   use Test::More;
   use feature 'say';
   use strict;
   use warnings;

   my $valid_host = qr/
      (?: $RE{net}{IPv6} ) |
      (?: $RE{net}{IPv4} ) |
      (?: $RE{net}{domain}{-nospace}{-rfc1101}\.? )
   /msx;

   my $hostname_long = hostname_long();
   warn "hostname_long [$hostname_long]";

   like( $hostname_long, $valid_host, 'Valid hostname or ip returned' );

   done_testing;

Example:

   $ ./hostname.pl 
   hostname_long [luna.watson-wilson.ca] at ./hostname.pl line 17.
   ok 1 - Valid hostname or ip returned
   1..1

**Comment by flynn1973** [comment]
root@nimmsag: /home/tremch # ./hostname_test.pl
hostname: Not a recognized flag: -
hostname_long [Usage: hostname [-s] [Host].] at ./hostname_test.pl line 17.
ok 1 - Valid hostname or ip returned
1..1

**Comment by neilhwatson** [comment]
I see. The module attempts to run the command hostname with some switches, but AIX's hostname does not recognize them, returns the error msg to hostname_long. The OK is an error on my part (fix is below) but the problem remains the module does not know how to use the hostname command in AIX. From the sys::hostname::long module it looks like it issue the command 'hostname --fqdn' Is that valid in AIX? Should be simple to submit a fix, which you can patch by hand on your server for the time being.

https://github.com/scottp/sys-hostname-long/blob/master/lib/Sys/Hostname/Long.pm#L82

### fixed test script

Added regex anchors.

#!/usr/bin/perl

    use Sys::Hostname::Long 'hostname_long';
    use Regexp::Common qw/ net number /;
    use Test::More;
    use feature 'say';
    use strict;
    use warnings;

    my $valid_host = qr/\A
        (?: $RE{net}{IPv6} ) |
        (?: $RE{net}{IPv4} ) |
        (?: $RE{net}{domain}{-nospace}{-rfc1101}\.? )
    \Z/msx;

    my $hostname_long = hostname_long();
    warn "hostname_long [$hostname_long]";

    like( $hostname_long, $valid_host, 'Valid hostname or ip returned' );

    done_testing;

**Comment by flynn1973** [comment]
the aix  hostname command only knows the "-s" switch and nothing more, so you are right. i will fix this in Long.pm. i keep you updated.

**Comment by flynn1973** [comment]
replaced the command in line 82 of Long.pm with a valid aix command, still the same error.

**Comment by neilhwatson** [comment]
What does our test script return?

**Comment by flynn1973** [comment]
i added a aix test case in Long.pm.

.....
                } elsif ($^O eq 'IRIX') {       # XXX Patter match string !
                        $hostlong = dispatcher('exec_hostname');

                } elsif ($^O eq 'aix') {       # XXX Patter match string !
                        $hostlong = dispatcher('exec_hostname');

                } elsif ($^O eq 'cygwin') {
                        $hostlong = dispatcher('win32_registry1');

...

now the test script is working.

root@nimmsag: /usr/opt/perl5/lib/site_perl/5.20.1/Sys/Hostname # /home/tremch/hostname_test.pl
hostname_long [nimmsag] at /home/tremch/hostname_test.pl line 17.
ok 1 - Valid hostname or ip returned
1..1

**Comment by flynn1973** [comment]
quick update: data is now insertet in the database.  but there are a few curiositys. 

the promise_count table is still empty, so no promise related reports are possible.

delta_reporting=# SELECT * FROM "promise_counts";
 rowid | datestamp | hosts | kept | notkept | repaired
-------+-----------+-------+------+---------+----------
(0 rows)

the standard GMT offset value in the web interface forms is CET which seems a little bit odd in view of the fact that this value is rejectet by the validator. 
i changed "string  => strftime( "localtime", "%Y-%m-%dT%H:%M:%S%z", now() );" to "string  => strftime( "localtime", "%Y-%m-%dT%H:%M:%S-100", now() );" in efl_common.cf, but now i'm not sure,  because to generate a report i have to change CET to +100? confusing... hen/egg problem?

**Comment by neilhwatson** [comment]
Promise_counts is a different table. Please use the cli or web query tools.

**Comment by neilhwatson** [comment]
Related to https://github.com/scottp/sys-hostname-long/issues/5

**Comment by flynn1973** [comment]
got a replay from ibm concerning the strftime case.

<snip>

Obviously it works like documented only when using the Unix 03 standard, means you need to set the environment variable
XPG_SUS_ENV=ON .
        If it is not set, it simply print the current TZ.
        I'll open a documentation APAR on Monday,
        Let me know if anything else.

</snip>

testet and confirmed.

root@nimmsag: /var/cfengine/masterfiles/itsv/not_working # ./strftime_test
Formatted date & time : |2016-11-28T09:42:11+0100|

so where in your code/architecture should this be set, since i can not set this globally on all my systems?

**Comment by flynn1973** [comment]
i let the delta reporting running over the weekend and it has filled up the database with a load of 13GB of data. unfortunatly there is still no promise data displayed only active/missing hosts. the promise chart is simply not there, and i can still not query promise related information. trending graph are also empty. i found out that the promise log file only contains this header, which looks not very promising *g*

root@nimmsag: /var/cfengine/delta_reporting/log # cat promises
BEGIN 2016-11-28T09:22:23+100

screenshots attached (ignore the missing hosts chart, its because the postgresql filesystem is full and i had to hard kill the delta reporting processes. did not expect that much data).
![home](https://cloud.githubusercontent.com/assets/14803546/20661763/b62825f4-b550-11e6-8cde-507058ed4f51.png)
![promise_report](https://cloud.githubusercontent.com/assets/14803546/20661771/bcad6916-b550-11e6-9e1f-823087813ac4.png)

**Comment by neilhwatson** [comment]
Thanks. I'm going to close this for now. Please keep me up to date on what IBM says.
