### ISSUE TITLE
promise table not gets populated, promise chart empty

### ISSUE THREAD

**Issue by flynn1973** [neilhwatson/delta_reporting#32]
i left the delta reporting running over the weekend and it has filled up the database with a load of 13GB of data. unfortunatly there is still no promise data displayed only active/missing hosts. the promise chart is simply not there, and i can still not query promise related information. trending graphs are also empty. i found out that the promise log file only contains this header, which looks not very promising g

root@nimmsag: /var/cfengine/delta_reporting/log # cat promises
BEGIN 2016-11-28T09:22:23+100

screenshots attached (ignore the missing hosts chart, its because the postgresql filesystem is full and i had to hard kill the delta reporting processes. did not expect that much data).

![home](https://cloud.githubusercontent.com/assets/14803546/20670531/86bd3740-b579-11e6-8c9e-9182ea5f6e3e.png)
![promise_report](https://cloud.githubusercontent.com/assets/14803546/20670530/86bc242c-b579-11e6-9147-75ca5f83f3f0.png)

 #31

**Comment by neilhwatson** [comment]
What tables are populated? Can you provide a sample of each? Can you provide a sample of the logs downloaded by the server? What do class reports show? What does the inventory report show?

**Comment by flynn1973** [comment]
only the "agent_log" table gets populated. the "promise_counts" table stays empty, and the "inventory_table" seems to contain predefined data.

delta_reporting=# SELECT * FROM "agent_log";
 timestamp        | promise_outcome
-------------------------------------------------------------------------------------------------------------+----------+---------------+----------------+----------+----------+---------------+--------+------
------------------+-----------------
 aix_powerpc_7_2_7                                                                                           | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      1 | 2016-
11-28 12:53:16+01 | empty
 have_fs_kind                                                                                                | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      2 | 2016-
11-28 12:53:16+01 | empty
 November                                                                                                    | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      3 | 2016-
11-28 12:53:16+01 | empty
 have_fs___mounts_205__2_____mounts_205__1__                                                                 | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      4 | 2016-
11-28 12:53:16+01 | empty
 have_fs___mounts_15__1__                                                                                    | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      5 | 2016-
11-28 12:53:16+01 | empty
 ipv4_172_16                                                                                                 | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      6 | 2016-
11-28 12:53:16+01 | empty
 services_autorun                                                                                            | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      7 | 2016-
11-28 12:53:16+01 | empty
 have_fs__                                                                                                   | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      8 | 2016-
11-28 12:53:16+01 | empty
 have_fs_Licensed                                                                                            | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |      9 | 2016-
11-28 12:53:16+01 | empty
 _stdlib_path_exists_df                                                                                      | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |     10 | 2016-
11-28 12:53:16+01 | empty
 _stdlib_has_path_diff                                                                                       | unknown  | 172.17.8.1    | empty          | empty    | empty    | nimmsag       |     11 | 2016-

delta_reporting=# SELECT * FROM "inventory_table";
 rowId |     class
-------+---------------
     1 | am_policy_hub
     2 | any
     3 | centos%
     4 | cfengine_3%
     5 | community%
     6 | debian%
     7 | enterprise%
     8 | fedora%
     9 | ipv4_%
    10 | linux%
    11 | policy_server
    12 | pure_%
    13 | redhat%
    14 | solaris%
    15 | sun4%
    16 | suse%
    17 | ubuntu%
    18 | virt_%
    19 | vmware%
    20 | xen%
    21 | zone_%
(21 rows)


delta_reporting=# SELECT * FROM "promise_counts";
 rowid | datestamp | hosts | kept | notkept | repaired
-------+-----------+-------+------+---------+----------
(0 rows)


donwloaded log sample:

root@nimmsag: /var/cfengine/delta_reporting/log/client_logs # cat 172.17.9.201.log
2016-11-28T12:53:40+0100 ;; aix_powerpc_7_2_7 ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs_kind ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; November ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs___mounts_15__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; ipv4_172_16 ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; services_autorun ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs__ ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs___mounts_199__2_____mounts_199__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs___mounts_55__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs_Licensed ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; _stdlib_path_exists_df ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; _stdlib_has_path_diff ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs___mounts_71__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs___mount ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; ipv4_172_16_13_201 ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; have_fs___mounts_208__1__ ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; _stdlib_has_path_logger ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; ipv4_172 ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; Day28 ;; empty ;; empty ;; empty ;; empty
2016-11-28T12:53:40+0100 ;; diskfree_high ;; empty ;; empty ;; empty ;; empty


class and inventory reports are working. dont have have screenshot of inventory report since i have stopped delta reporting temporarly.

![class](https://cloud.githubusercontent.com/assets/14803546/20671286/0bfcc530-b57d-11e6-9e81-cb127dc1e539.PNG)

one thing, could it be that delta reporting does not work with promises run by cfengine autorun mechanism? i do not use efl for bundles or something but rather only the standard cfengine autorun.

root@nimmsag: /var/cfengine/delta_reporting/log/client_logs # /var/cfengine/bin/cf-agent -KI
Active Memory Expansion        : Disabled
    info: Installing cfe_internal_non_existing_package...
    info: Deleted file '/var/cfengine/outputs/cf_nimmsag__1480083177_Fri_Nov_25_15_12_57_2016_235'
R: Garbage Collection was done at ( Mon Nov 28 15:15:32 2016 ).
R: ITSV hostgroup:  VIE
R: ITSV hostgroup:  SAP_HOST
R: ITSV hostgroup:  SECURE_LAN
R: ITSV hostgroup:  WGKK_LAN
    info: Setting field sub-value 'local4, bind4' in '/etc/netsvc.conf'
    info: Edited field inside file object /etc/netsvc.conf
R: test policy was triggered at ( Mon Nov 28 15:15:32 2016 ).
R: autorun is executing
R: default:G_garbage_collection: found bundle default:G_garbage_collection
R: default:b0001_itsv_hostgroups_reporting: found bundle default:b0001_itsv_hostgroups_reporting
R: default:b0002_itsv_trim_inetd_services: found bundle default:b0002_itsv_trim_inetd_services
R: default:b0003_itsv_rootvg_files: found bundle default:b0003_itsv_rootvg_files
R: default:b0004_itsv_sync_sudoers: found bundle default:b0004_itsv_sync_sudoers
R: default:b0005_itsv_config_ntp: found bundle default:b0005_itsv_config_ntp
R: default:b0006_itsv_free_nfs_mounts: found bundle default:b0006_itsv_free_nfs_mounts
R: default:b0007_itsv_user_management: found bundle default:b0007_itsv_user_management
R: default:b0008_itsv_root_auth_keys: found bundle default:b0008_itsv_root_auth_keys
R: default:b0009_cferoot_dist: found bundle default:b0009_cferoot_dist
R: default:b0010_itsv_sshd_config: found bundle default:b0010_itsv_sshd_config
R: default:b0011_itsv_start_services_ldap: found bundle default:b0011_itsv_start_services_ldap
R: default:b0012_itsv_start_services_nmon: found bundle default:b0012_itsv_start_services_nmon
R: default:b0013_itsv_config_netsvc: found bundle default:b0013_itsv_config_netsvc
R: default:b0014_itsv_rc_shutdown: found bundle default:b0014_itsv_rc_shutdown
R: default:b0015_itsv_sys_attributes: found bundle default:b0015_itsv_sys_attributes
R: default:b0016_user_limits: found bundle default:b0016_user_limits
R: default:b0017_itsv_tlmagent_config: found bundle default:b0017_itsv_tlmagent_config
R: default:b0018_start_services_tlmagent: found bundle default:b0018_start_services_tlmagent
R: default:b0019_itsv_config_largesend: found bundle default:b0019_itsv_config_largesend
R: default:b0020_itsv_syslog_conf: found bundle default:b0020_itsv_syslog_conf
R: default:b0021_itsv_cl_rg_move_check: found bundle default:b0021_itsv_cl_rg_move_check
R: default:b0022_control_cluster_doku: found bundle default:b0022_control_cluster_doku
R: default:b0023_itsv_config_passwd_algo: found bundle default:b0023_itsv_config_passwd_algo
R: default:b0024_dr_watson: found bundle default:b0024_dr_watson
R: default:b0025_sendmail_config: found bundle default:b0025_sendmail_config
R: default:b0027_git_update: found bundle default:b0027_git_update
R: default:b0028_control_lpar2rrd: found bundle default:b0028_control_lpar2rrd
R: default:b0029_set_preferred_read2local_box: found bundle default:b0029_set_preferred_read2local_box
R: default:b0031_control_update_aix_sp7: found bundle default:b0031_control_update_aix_sp7
R: default:b0032_control_distribute_project_files: found bundle default:b0032_control_distribute_project_files
R: default:b0033_control_sort_filesystems: found bundle default:b0033_control_sort_filesystems
R: default:b0034_itsv_config_polluplink: found bundle default:b0034_itsv_config_polluplink
R: default:ctremel_test: found bundle default:ctremel_test
R: default:sleep3605: found bundle default:sleep3605

**Comment by neilhwatson** [comment]
CFEngine community does not offer any automatic promise logging. EFL promises do provide promise logging, when using EFL promises. Non EFL promise do not log anything, and thus are not be inserted into DR's database. What you see in your agent log are classes.

All global classes are captured that end of the run by the post logging bundle and put into a raw log.
Promises can only go into the raw log if they use the mechanism that EFL uses, custom action and classes bodies. So you must use EFL promises or rewrite your own to use the same action and classes bodies as EFL.

https://github.com/neilhwatson/delta_reporting#note-about-efl

Low level details:
https://github.com/neilhwatson/evolve_cfengine_freelib/blob/master/masterfiles/lib/3.7/EFL/evolve_freelib.cf#L2280-L2281

**Comment by flynn1973** [comment]
wow...that hurts. i dont think i can use only the efl library for my promises since my bundles needs/depends also on the cfengine standrad library.

**Comment by neilhwatson** [comment]
If you want every promise you ever write to log, without any custom work, you need to buy CFEngine Enterprise. DR is an alternative, but not without some cost. Still EFL's bundles are meant to handle 90% of ones needs. It's very rare that I have to write a special case bundles.

If you alter your existing promises then they too will log like EFL, but it might be simpler to obsolete your promises in favour of EFL's.

**Comment by neilhwatson** [comment]
You can find me on #cfengine if you want to chat about this.

**Comment by flynn1973** [comment]
it was already discussed to buy cfengine enterprise. thats the reason i was pushed to test out "alternatives". 
the problem now is, i dont even know how to run a simple bundle within this efl wizardy. i browsed the doc files but found not one usable template. or am i looking in the wrong places?

**Comment by neilhwatson** [comment]
What have you looked at? EFL is like CFEngine in that you have think differently, but once you do it's simple. The idea is that all bundles are data driven, reusable, and geared toward generic purposes. Promise a running service, promise files are copied, promise file permissions, promise kernel settings, promise to run commands, promise to set soft classes. Each of those bundles takes parameter data in the form of a json.

**Comment by neilhwatson** [comment]
Essentially

    methods:

       "file perms for hardening" -> { "infosec" }
          usebundle => efl_file_perms( "/var/cfengine/inputs/elf_data/perms1.json" );

Where perms1.json looks like:

    [
       {
          "owner" : "neil",
          "group" : "neil",
          "class" : "any",
          "file_promiser" : "/home/neil/.ssh",
          "mode" : "600",
          "promisee" : "Neil Watson",
          "negate" : "no",
          "recurse_level" : "inf",
          "leaf_regex" : ".*"
       },
       {
           "owner" : "root",
           "group" : "root",
           "class" : "any",
           "file_promiser" : "/root/",
           "mode" : "o-rwx",
           "promisee" : "general hardening",
           "negate" : "no",
           "recurse_level" : "inf",
           "leaf_regex" : ".*"
       }
    ]

Add more docs in the above array for more file perms promises.

The bundle efl_main offers similar abstraction to the methods call above:

    methods:
       "all bundles"
          usebundle => efl_main( "/var/cfengine/inputs/efl_data/efl_main.json" );

Where efl_main.json looks like this:

    [
       {
          "promiser" : "delta reporting prelog setup",
          "class" : "any",
          "ifelapsed" : "1",
          "bundle" : "deltarep_prelogging",
          "promisee" : "delta reporting",
          "parameter" : "null"
       },
       {
          "promiser" : "file perms for hardening",
          "class" : "any",
          "ifelapsed" : "1",
          "bundle" : "efl_file_perms",
          "promisee" : "infosec",
          "parameter" : "/var/cfengine/inputs/efl_data/perms1.json"
       },
    ]

Add more docs in the array to add more method calls.

**Comment by flynn1973** [comment]
hmm...ok this helps. but the question is, can i run my bundles through this mechanism unmodified, or are only efl bundles allowed.

for instance, i have a bundle "efl_test", can i do this?

`
[
      {
      "promiser" : "efl_test",
      "class" : "any",
      "ifelapsed" : "1",
      "bundle" : "efl_test",
      "promisee" : "noob",
      "parameter" : "null"
   },
]
`

**Comment by flynn1973** [comment]
i answer myself...it seems not to. since rewriting all bundles to efl nomenclatura is  not an option, i fear the journey has come to an end here.

root@nimmsag: /var/cfengine/outputs # cat cf_nimmsag__1480423091_Tue_Nov_29_13_38_11_2016_141
Active Memory Expansion        : Disabled
   error: While constructing scope 'efl_test'
Formal =  {}, Actual =  {'lawrence'}
   error: Fatal CFEngine error: Augment scope, formal and actual parameter mismatch is fatal

**Comment by neilhwatson** [comment]
You only need to make one small change to run your bundles via efl_main

Your old bundle:

    bundle agent mine {

Your new bundle:

    bundle agent mine ( this_var_not_used ) {

You need only add a paramater that will never be used. Still the promises inside the bundle will not log outcomes unless you change them or retire them and use EFL bundles.

**Comment by flynn1973** [comment]
meanwhile i tried it the other way around and added the efl logging classes in one of my bundles. i wait eagerly what absurd things will happen now. 

bundle agent b0027_git_update
    {

 # this triggers the autorun shit
 meta:
    "tags"  slist => { "itsv" };

  classes:
    "percent_of_runs"
     dist => { "15", "85" };

   
  commands:

     percent_of_runs_15.policy_server::

        "/usr/bin/git"
          args => "pull --ff-only origin master",
          handle     => "git_update",
          classes    => efl_rkn( "/usr/bin/git", "git_update" ),
          action     => efl_delta_reporting( "/usr/bin/git", "git_update", "${d[${i}][promisee]}", "1" ),
          contain => masterfiles_contain;


  reports:

    percent_of_runs_15.policy_server::

      "git masterfiles pull was triggered at ( $(sys.date) ).";

     delta_reporting::
         "itsv_git_update_ok ;; ${d[${i}][command]} ;; ${d[${i}][promisee]}" -> { "${d[${i}][promisee]}" }
            handle         => "git_update_log_promises",
            ifvarclass     => canonify( "${d[${i}][command]}_handle_git_update_ok_kept" ),
            report_to_file => "${efl_c.promise_log}";



    }

    body contain masterfiles_contain
    {
      chdir => "/var/cfengine/masterfiles/itsv";
    }

**Comment by flynn1973** [comment]
surprise, at least something has happened in the promise log file.

root@nimmsag: /var/cfengine/delta_reporting/log # cat promises
BEGIN 2016-11-29T15:32:45+0100
/usr/bin/git ;; git_update ;; ${d[${i}][promisee]}

**Comment by neilhwatson** [comment]
I'm not certain of code's intentions, but I don't think the reports promise is needed. Actions => efl_delta_reporting writes to the log. Also ${d[${i}][promisee]} has to have some definition. And the args for the actions bundle are handle, promiser, promisee, ifelapsed.  The example has handle and promiser reversed.

https://github.com/neilhwatson/evolve_cfengine_freelib/blob/master/masterfiles/lib/3.7/EFL/evolve_freelib.cf#L2633

**Comment by neilhwatson** [comment]
FYI EFL does have an rcs bundle that you can use or learn from:

https://github.com/neilhwatson/evolve_cfengine_freelib/blob/master/masterfiles/lib/3.7/EFL/evolve_freelib.cf#L2659

**Comment by flynn1973** [comment]
success! promise reports are working now.
![promise_report](https://cloud.githubusercontent.com/assets/14803546/20743685/08e50054-b6d8-11e6-8bfd-e569cbe87d40.png)

thank your very much for your help and patience!

one little thing, what could be the reason that the hostname field shows unknown?

**Comment by neilhwatson** [comment]
Hostname comes for PTR lookups of the IP address.

 Please ensure that you run delta-cron daily. See 'Help' in the web interface.

https://github.com/neilhwatson/delta_reporting/blob/a5065d3e3ff1ada29eefa3b94589a9a622e006c8/app/script/delta-cron

**Comment by flynn1973** [comment]
i greped after the perl reverse lookup function but cannot find a trace of it .

root@nimmsag: /opt/delta_reporting/app # grep -r gethostbyaddr *

do you use something other?

at least reverse lookups through perl are working...

root@nimmsag: /opt/delta_reporting/app # perl -MSocket -E 'say scalar gethostbyaddr(inet_aton("172.17.8.1"), AF_INET)'
nimmsag_a
root@nimmsag: /opt/delta_reporting/app # perl -MSocket -E 'say scalar gethostbyaddr(inet_aton("172.16.156.14"), AF_INET)'
aixtest01.test.sozvers.at

**Comment by neilhwatson** [comment]
https://github.com/neilhwatson/delta_reporting/blob/master/app/lib/DeltaR/Query.pm#L506

https://github.com/neilhwatson/delta_reporting/blob/master/app/lib/DeltaR/Query.pm#L625

**Comment by flynn1973** [comment]
strange..the net::dns module does not return a hostname here


i replaced it with something simpler and this works.

sub _get_ptr {
      my $ip = shift;
      my $hostname = 'unknown';
      $hostname=gethostbyaddr(inet_aton($ip), AF_INET);
       return $hostname;
    }


![promise_report](https://cloud.githubusercontent.com/assets/14803546/20757790/f3a206e8-b717-11e6-8299-cb7fe5616a06.png)

**Comment by neilhwatson** [comment]
Can you test that change with ipv6?

**Comment by flynn1973** [comment]
sorry no, because ipv6 is massively broken on this damned aix platform.
