### ISSUE TITLE
Try this get ptr sub instead

### ISSUE THREAD

**Issue by neilhwatson** [neilhwatson/delta_reporting#33]
Because the existing one does not work AIX.   

    sub _get_ptr {
        my $ip = shift;
        my $hostname = 'unknown';
        $hostname=gethostbyaddr(inet_aton($ip), AF_INET);
        return $hostname;
    }

**Comment by neilhwatson** [comment]
see #32

**Comment by neilhwatson** [comment]
@flynn1973 Please try t/15_network.t on AIX.

https://github.com/neilhwatson/delta_reporting/blob/master/app/t/15_network.t

**Comment by flynn1973** [comment]
root@nimmsag: /root # perl -I/opt/delta_reporting/app/lib network_test.pl
1..3
FQDN is nimmsag at network_test.pl line 29.
ip is 2a02:2770:5:0:21a:4aff:fe5a:b988 at network_test.pl line 35.
Use of uninitialized value in gethostbyaddr at /opt/delta_reporting/app/lib/DeltaR/Query.pm line 648.
Use of uninitialized value $ptr_fqhn in concatenation (.) or string at network_test.pl line 39.
final hostname is  at network_test.pl line 39.
ok 1 - Sys::Hostname::Long Can resolve hostname
ok 2 - Can resolve ip address
not ok 3 - DeltaR::Query::_get_ptr returns fqhn
#   Failed test 'DeltaR::Query::_get_ptr returns fqhn'
#   at network_test.pl line 43.
#                   undef
#     doesn't match '(?^x:\A (?:(?!(?:(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}))(?:[.]|$))[A-Za-z0-9](?:(?:[-A-Za-z0-9]){0,61}[A-Za-z0-9])?(?:\.(?!(?:(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}))(?:[.]|$))[A-Za-z0-9](?:(?:[-A-Za-z0-9]){0,61}[A-Za-z0-9])?)*)\.? \Z)'
# Looks like you failed 1 test of 3.

**Comment by neilhwatson** [comment]
Be sure to run the test from a full clone of the latest master. The error message mentioning line 648 suggests your copy is different from master.

git clone ...
cd app/
t/15_network.t
