### ISSUE TITLE
Add Test that %z returns numeric timezone

### ISSUE THREAD

**Issue by neilhwatson** [neilhwatson/delta_reporting#35]

**Comment by neilhwatson** [comment]
@flynn1973 Can you provide a none C compiling test that %z renders a numeric timezone? I don't use AIX often. Can you duplicate with date +%z ?

**Comment by flynn1973** [comment]
the both do not return numeric values.

root@nimmsag: /var/cfengine/delta_reporting/log/client_logs #  date +%z
CET
root@nimmsag: /var/cfengine/delta_reporting/log/client_logs #  date +%Z
CET
