### ISSUE TITLE
delta-cron causes deadlock on database

### ISSUE THREAD

**Issue by flynn1973** [neilhwatson/delta_reporting#36]
while running delta-cron there are a lot of hanging REINDEX processes.

root@nimmsag: /var/cfengine/outputs # ps -ef | grep post | grep REINDEX
postgres  6619626 33489360   0 06:43:42      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(33630) REINDEX waiting
postgres 11075984 33489360   0 05:26:07      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(62136) REINDEX waiting
postgres 12452148 33489360   0 03:59:39      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(54932) REINDEX waiting
postgres 13566342 33489360   0 03:51:34      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(54552) REINDEX waiting
postgres 13959532 33489360   0 23:46:32      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(40395) REINDEX waiting
postgres 14614880 33489360   0 02:50:21      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(50222) REINDEX waiting
postgres 15860210 33489360   0 03:08:17      -  0:02 postgres: deltar_rw delta_reporting 127.0.0.1(51255) REINDEX waiting
postgres 16908650 33489360   0 01:29:43      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(46105) REINDEX waiting
postgres 18350590 33489360   0 04:17:13      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(56830) REINDEX waiting
postgres 20251072 33489360   0 02:58:32      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(50591) REINDEX waiting
postgres 21234098 33489360   0 06:35:48      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(33282) REINDEX waiting
postgres 22217122 33489360   0 06:59:48      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(34436) REINDEX waiting
postgres 22610416 33489360   0 07:08:03      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(34900) REINDEX waiting
postgres 23069120 33489360   0 04:26:23      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(57979) REINDEX waiting
postgres 24576410 33489360   0 04:43:43      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(59424) REINDEX waiting
postgres 25297166 33489360   0 00:49:05      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(43632) REINDEX waiting
postgres 25493942 33489360   0 04:35:20      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(58648) REINDEX waiting
postgres 28377560 33489360   0 02:26:11      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(49022) REINDEX waiting
postgres 29163844 33489360   0 01:21:43      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(45739) REINDEX waiting
postgres 30277960 33489360   0 01:46:11      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(46954) REINDEX waiting
postgres 32768408 33489360   0 03:43:01      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(54108) REINDEX waiting
postgres 33882472 33489360   0 06:09:25      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(64700) REINDEX waiting
postgres 34668914 33489360   0 07:16:24      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(35366) REINDEX waiting
postgres 36831630 33489360  64 00:57:22      -  4:52 postgres: deltar_rw delta_reporting 127.0.0.1(44076) REINDEX
postgres 37290300 33489360   0 06:27:47      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(32844) REINDEX waiting
postgres 37683670 33489360   0 02:34:14      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(49393) REINDEX waiting
postgres 37749104 33489360   0 00:19:27      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(42083) REINDEX waiting
postgres 38011190 33489360   0 00:37:21      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(43076) REINDEX waiting
postgres 38535514 33489360   0 05:50:03      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(63661) REINDEX waiting
postgres 39059964 33489360   0 03:34:55      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(53703) REINDEX waiting
postgres 39190812 33489360   0 04:52:20      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(59993) REINDEX waiting
postgres 39584106 33489360   0 01:38:08      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(46534) REINDEX waiting
postgres 39649706 33489360   0 06:19:30      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(65208) REINDEX waiting
postgres 40042854 33489360   0 05:42:09      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(63271) REINDEX waiting
postgres 40763878 33489360   0 05:58:08      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(64040) REINDEX waiting
postgres 42074532 33489360   0 05:17:55      -  0:00 postgres: deltar_rw delta_reporting 127.0.0.1(61692) REINDEX waiting

the log shows a deadlock

ERROR:  deadlock detected at character 13
DETAIL:  Process 19988836 waits for RowExclusiveLock on relation 33098 of database 16386; blocked by process 22086098.
        Process 22086098 waits for AccessExclusiveLock on relation 33105 of database 16386; blocked by process 19988836.
        Process 19988836: DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
        Process 22086098: REINDEX TABLE agent_log
HINT:  See server log for query details.
STATEMENT:  DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
ERROR:  deadlock detected at character 13
DETAIL:  Process 18088264 waits for RowExclusiveLock on relation 33098 of database 16386; blocked by process 22086098.
        Process 22086098 waits for AccessExclusiveLock on relation 33105 of database 16386; blocked by process 18088264.
        Process 18088264: DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
        Process 22086098: REINDEX TABLE agent_log
HINT:  See server log for query details.
STATEMENT:  DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
ERROR:  deadlock detected at character 13
DETAIL:  Process 5833094 waits for RowExclusiveLock on relation 33098 of database 16386; blocked by process 22086098.
        Process 22086098 waits for AccessExclusiveLock on relation 33105 of database 16386; blocked by process 5833094.
        Process 5833094: DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
        Process 22086098: REINDEX TABLE agent_log
HINT:  See server log for query details.
STATEMENT:  DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
ERROR:  deadlock detected at character 13
DETAIL:  Process 13173034 waits for RowExclusiveLock on relation 33098 of database 16386; blocked by process 35324214.
        Process 35324214 waits for AccessExclusiveLock on relation 33105 of database 16386; blocked by process 13173034.
        Process 13173034: DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'
        Process 35324214: REINDEX TABLE agent_log
HINT:  See server log for query details.
STATEMENT:  DELETE FROM agent_log WHERE timestamp < now()
                 - interval '3 days'

why is this REINDEX needed? setting autovacuum in postgresql should normaly be enough.

**Comment by neilhwatson** [comment]
How many cf-agent hosts do you have? I don't have the resources to test larger scale deployments. It might be related to constant writes from incoming logs contending with the cron job. Yes, REINDEX might not be required. Try disabling REINDEX and run again.

**Comment by flynn1973** [comment]
i have about 400 aix clients running. what function triggers the reindex (prune or delete or both).
i have enabled autovacuum in postgresql.

#------------------------------------------------------------------------------
# AUTOVACUUM PARAMETERS
#------------------------------------------------------------------------------

autovacuum = on                         # Enable autovacuum subprocess?  'on'
                                        # requires track_counts to also be on.
log_autovacuum_min_duration = 0         # -1 disables, 0 logs all actions and
                                        # their durations, > 0 logs only
                                        # actions running at least this number
                                        # of milliseconds.
autovacuum_max_workers = 6              # max number of autovacuum subprocesses
                                        # (change requires restart)
autovacuum_naptime = 15s                # time between autovacuum runs
autovacuum_vacuum_threshold = 25        # min number of row updates before
                                        # vacuum
autovacuum_analyze_threshold = 10       # min number of row updates before
                                        # analyze
autovacuum_vacuum_scale_factor = 0.1    # fraction of table size before vacuum
autovacuum_analyze_scale_factor = 0.05  # fraction of table size before analyze
#autovacuum_freeze_max_age = 200000000  # maximum XID age before forced vacuum
                                        # (change requires restart)
#autovacuum_multixact_freeze_max_age = 400000000        # maximum Multixact age
                                        # before forced vacuum
                                        # (change requires restart)
autovacuum_vacuum_cost_delay = 10ms     # default vacuum cost delay for
                                        # autovacuum, in milliseconds;
                                        # -1 means use vacuum_cost_delay
autovacuum_vacuum_cost_limit = 1000     # default vacuum cost limit for
                                        # autovacuum, -1 means use
                                        # vacuum_cost_limit

**Comment by neilhwatson** [comment]
https://github.com/neilhwatson/delta_reporting/blob/a5065d3e3ff1ada29eefa3b94589a9a622e006c8/app/lib/DeltaR/Query.pm#L54

**Comment by flynn1973** [comment]
changed REINDEX to ANALYZE as recommended by the postgres folks...

sub table_cleanup {
   my $self = shift;
   my $return;
   my @clean_operations = (
      "VACUUM $agent_table{$self}",
      "ANALYZE $agent_table{$self}",
   );

**Comment by neilhwatson** [comment]
Ok, try it out for a few days and let me know the results.

**Comment by flynn1973** [comment]
i will make a pull request with all the changes made, but i'm on holiday as of monday until middle  january 2017.

**Comment by neilhwatson** [comment]
No worries. Thanks for your feed back and patients.

**Comment by neilhwatson** [comment]
How did your testing turn out?

**Comment by flynn1973** [comment]
Well, not so good. One big problem ist that it takes about 40 minutes to pull the logs from the clients and insert into the database, and i only have about 400 clients for now. This resultsts in inaccurate counts of hosts and other weird outputs. The other thing is, only the first  policy in the raw log is inserted into the database, every other line is omiited. Management is also not very impressed about the fact that we have to mess around with every policy file  to make  the reporting work.
I’m not shure how to proceed here.

Christian Tremel
IT-Services der Sozialversicherung GmbH
RZ/AIX
Gruberstraße 77
A-4021 Linz
T: +43 (0) 50124 844 1266
M: +43 (0) 664 8866 1266
rz.aix<mailto:vorname.name@itsv.at>@itsv.at<mailto:genero.aix@ooegkk.at>
christian.tremel@itsv.at<mailto:christian.tremel@itsv.at>
www.itsv.at<http://www.itsv.at/> I www.intranet.itsv.at<http://www.intranet.itsv.at/>

[CIS-Logo-Signatur]

Von: Neil H Watson [mailto:notifications@github.com]
Gesendet: Samstag, 21. Jänner 2017 15:24
An: neilhwatson/delta_reporting <delta_reporting@noreply.github.com>
Cc: Tremel Christian <Christian.Tremel@itsv.at>; Author <author@noreply.github.com>
Betreff: Re: [neilhwatson/delta_reporting] delta-cron causes deadlock on database (#36)


How did your testing turn out?

**Comment by neilhwatson** [comment]
Can you provide more detail? I don't know why it would take 40m to download 400 files. I don't understand the rest of your message.
